---
- name: Patch RHEL Servers
  hosts: all

  roles:
    - { role: shadowman_patching, when: "'foreman_hostcollection_patching' in group_names" }

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_linux_patch
        apply:
          delegate_to: "{{ groups['foreman_hostcollection_reporting'][0] }}"
          run_once: true
